from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from audioforge.app.models.audio_project import AudioProject
from audioforge.app.models.experiment_workspace import ExperimentTask, ExperimentVariant, ExperimentWorkspace
from audioforge.app.services.recovery_service import RecoverySnapshot


class ProjectRepository(Protocol):
    def exists(self, file_path: str) -> bool: ...

    def is_file(self, file_path: str) -> bool: ...

    def load(self, file_path: str) -> AudioProject: ...

    def save(self, project: AudioProject, file_path: str) -> str: ...

    def resolve_save_path(self, file_path: str | None, suggested_name: str) -> str | None: ...


class ExperimentWorkspaceRepository(Protocol):
    def create(self, workspace_path: str, base_project_path: str, name: str) -> ExperimentWorkspace: ...

    def load(self, path: str) -> ExperimentWorkspace: ...

    def save(self, workspace: ExperimentWorkspace) -> None: ...

    def create_task(self, workspace: ExperimentWorkspace, name: str, variant_name: str) -> ExperimentTask: ...

    def delete_task(self, workspace: ExperimentWorkspace, task_index: int) -> None: ...

    def create_variant(self, workspace: ExperimentWorkspace, task_index: int, variant_name: str) -> ExperimentVariant: ...

    def duplicate_variant(
        self,
        workspace: ExperimentWorkspace,
        task_index: int,
        variant_index: int,
        new_name: str,
    ) -> ExperimentVariant: ...

    def delete_variant(self, workspace: ExperimentWorkspace, task_index: int, variant_index: int) -> None: ...

    def sync_variant_from_base(self, workspace: ExperimentWorkspace, task_index: int, variant_index: int) -> str | None: ...


class SnapshotRepository(Protocol):
    def has_snapshot(self) -> bool: ...

    def exists(self, snapshot_path: str) -> bool: ...

    def save_snapshot(self, project: AudioProject) -> str: ...

    def save_history_snapshot(self, project: AudioProject, *, max_entries: int = 10) -> str: ...

    def load_snapshot(self, snapshot_path: str | None = None) -> RecoverySnapshot: ...

    def list_history_snapshots(self) -> list[str]: ...

    def clear_snapshot(self) -> None: ...


class SettingsStore(Protocol):
    def get_value(self, key: str, default: Any = None) -> Any: ...

    def set_value(self, key: str, value: Any) -> None: ...


class PlaybackGateway(Protocol):
    def play_file(
        self,
        file_path: str,
        *,
        event_id: str,
        volume_db: float,
        pitch_cents: int,
        trim_start_ms: int,
        trim_end_ms: int,
        fade_in_ms: int,
        fade_out_ms: int,
    ) -> str: ...

    def stop_event(self, event_id: str) -> None: ...

    def stop_oldest(self, event_id: str) -> None: ...

    def has_active_event(self, event_id: str) -> bool: ...

    def is_event_paused(self, event_id: str) -> bool: ...

    def pause_event(self, event_id: str) -> bool: ...

    def resume_event(self, event_id: str) -> bool: ...

    def stop_buses(self, bus_names: list[str]) -> None: ...

    def refresh_bus_volumes(self, resolver: Callable[[str], float]) -> None: ...