from __future__ import annotations

from pathlib import Path

APP_NAME = "AudioForge"
APP_VERSION = "0.06.0"
PROJECT_EXTENSION = ".afproj"
SCHEMA_VERSION = 1
PROJECT_VERSION = 1
DEFAULT_BUSES = ["BGM", "SFX", "UI"]
DEFAULT_EXPORT_DIRNAME = "Export"
DEFAULT_RUNTIME_DATA_FILENAME = "AudioData.json"
DEFAULT_EVENT_ENUM_FILENAME = "AudioEventID.cs"
DEFAULT_BUILD_REPORT_FILENAME = "BuildReport.json"
DEFAULT_AUDIO_MANIFEST_FILENAME = "AudioManifest.json"
DEFAULT_EXPORT_ASSETS_DIRNAME = "Assets"
SUPPORTED_AUDIO_EXTENSIONS = {".wav", ".ogg"}
SUPPORTED_SOURCE_AUDIO_EXTENSIONS = {".wav", ".ogg"}
SUPPORTED_RUNTIME_AUDIO_FORMATS = ["ogg", "wav"]
DEFAULT_WINDOW_SIZE = (1440, 900)
DEFAULT_PROJECT_NAME = "UntitledProject"
DEFAULT_EXPORT_ROOT = Path(DEFAULT_EXPORT_DIRNAME)

MIN_VOLUME_DB = -96.0
MAX_VOLUME_DB = 12.0
MIN_PITCH_CENTS = -2400
MAX_PITCH_CENTS = 2400
MIN_COOLDOWN_SECONDS = 0.0
MAX_COOLDOWN_SECONDS = 60.0
MIN_MAX_INSTANCES = 0
MAX_MAX_INSTANCES = 999
MIN_COMBO_MAX_STEP = 0
MAX_COMBO_MAX_STEP = 999
MIN_CLIP_WEIGHT = 1
MAX_CLIP_WEIGHT = 100
CLIP_WEIGHT_PRESETS = [1, 2, 5, 10, 20, 50, 100]
MIN_CLIP_TIME_MS = 0
MAX_CLIP_TIME_MS = 999999

WWISE_MASTER_MIXER_TITLE = "Bus 混音台"
WWISE_MASTER_MIXER_HIERARCHY_TITLE = "Bus 层级"
WWISE_PROPERTY_EDITOR_TITLE = "属性编辑器"
WWISE_TRANSPORT_TITLE = "传输控制"
WWISE_MASTER_AUDIO_BUS_TITLE = "主 Bus"
WWISE_OUTPUT_BUS_LABEL = "输出 Bus"
WWISE_TARGET_BUS_LABEL = "目标 Bus"
WWISE_DEFAULT_BUS_LABEL = "默认 Bus"
WWISE_BUS_NAME_LABEL = "Bus 名称"
WWISE_PARENT_BUS_LABEL = "父 Bus"
WWISE_ROUTING_LABEL = "路由"
WWISE_CHILD_BUSES_LABEL = "子 Bus"
WWISE_EFFECTIVE_OUTPUT_LABEL = "有效输出"
WWISE_BUS_VIEW_LABEL = "Bus 视图"
WWISE_BUS_WORKSPACE_KEYWORDS = "bus混音台 bus 混音台 master-mixer master mixer 总线 混音 bus层级 bus 层级 bus视图 bus 视图 输出bus 输出 bus 默认bus 默认 bus 父bus 父 bus 子bus 子 bus 主bus 主 bus 路由 属性编辑器 传输控制"
WWISE_BUS_SEARCH_KEYWORDS = "bus 总线 路由 bus视图 bus 视图 输出bus 输出 bus 默认bus 默认 bus 父bus 父 bus 子bus 子 bus 主bus 主 bus"
WWISE_RESOURCES_BATCH_FEEDBACK_KEYWORDS = "批量反馈 最近批量 批量编辑反馈 批处理反馈 batch feedback recent batch"