from __future__ import annotations

from pathlib import Path

APP_NAME = "AudioForge"
APP_VERSION = "0.05"
PROJECT_EXTENSION = ".afproj"
SCHEMA_VERSION = 1
PROJECT_VERSION = 1
DEFAULT_BUSES = ["BGM", "SFX", "UI"]
DEFAULT_EXPORT_DIRNAME = "Export"
DEFAULT_RUNTIME_DATA_FILENAME = "AudioData.json"
DEFAULT_EVENT_ENUM_FILENAME = "AudioEventID.cs"
DEFAULT_BUILD_REPORT_FILENAME = "BuildReport.json"
DEFAULT_AUDIO_MANIFEST_FILENAME = "AudioManifest.json"
DEFAULT_EXPORT_ASSETS_DIRNAME = "Assets"
SUPPORTED_AUDIO_EXTENSIONS = {".wav", ".ogg"}
SUPPORTED_SOURCE_AUDIO_EXTENSIONS = {".wav", ".ogg"}
SUPPORTED_RUNTIME_AUDIO_FORMATS = ["ogg", "wav"]
DEFAULT_WINDOW_SIZE = (1440, 900)
DEFAULT_PROJECT_NAME = "UntitledProject"
DEFAULT_EXPORT_ROOT = Path(DEFAULT_EXPORT_DIRNAME)

MIN_VOLUME_DB = -96.0
MAX_VOLUME_DB = 12.0
MIN_PITCH_CENTS = -2400
MAX_PITCH_CENTS = 2400
MIN_COOLDOWN_SECONDS = 0.0
MAX_COOLDOWN_SECONDS = 60.0
MIN_MAX_INSTANCES = 0
MAX_MAX_INSTANCES = 999
MIN_COMBO_MAX_STEP = 0
MAX_COMBO_MAX_STEP = 999
MIN_CLIP_WEIGHT = 1
MAX_CLIP_WEIGHT = 100
CLIP_WEIGHT_PRESETS = [1, 2, 5, 10, 20, 50, 100]
MIN_CLIP_TIME_MS = 0
MAX_CLIP_TIME_MS = 999999